export type themeType =
  | "Modern"
  | "Vintage"
  | "Minimalist"
  | "Professional"
  | "Tropical";

export type roomType =
| "LIVING ROOM"
| "INDOOR POOL"
| "OCEAN VIEW VILLA"
| "CHILDREN'S ROOM"
| "MODERN KITCHEN"
| "LUXURY BATHROOM"
| "HOME OFFICE"
| "MODERN BEDROOM"
| "COURTYARD"
| "OUTDOOR CAFETERIA"
| "ATTIC KITCHEN - MARUTI"
| "BACKYARD GARDEN"
| "TROPICAL BATHROOM"
| "LUXURY BEDROOM"
| "LUXURY YACHT"
| "BOHEMIAN BEDROOM"
| "RESTAURANT"
| "LUXURY HOTEL RECEPTION"
| "INDIAN LIVING ROOM"
| "MODERN LIVING ROOM"
| "LUXURY BATHROOM"
| "INDIAN KITCHEN"
| "LUXURY DINING ROOM"
| "SUN ROOM"
| "BASEMENT"
| "LUXURY GARAGE"
| "CLUB HOUSE"
| "VICTORIAN MUSIC ROOM"
| "CONFERENCE ROOM"
| "HOME CASINO"
| "MINI MART"
| "MOROCCAN KITCHEN"
| "BABY BOY'S ROOM"
| "DENTIST RECEPTION AREA"
| "LAUNDRY ROOM"
| "ATTIC"
| "ARCADE LOUNGE"
| "HOME GYM"
| "SALON"
| "HOME LIBRARY"
| "OFFICE CABIN"
| "PRIVATE STUDY ROOM"
| "TERRACE"
| "HOTEL ROOM"
| "OFFICE LIBRARY"
| "RUSTIC CABIN"
| "RESTAURANT"
| "OFFICE LOBBY"
| "MODERN BEACH HOUSE"
| "TEA ROOM"
| "MODERN MUSIC ROOM"
| "OFFICE LOUNGE"
| "BALCONY"
| "TREE HOUSE"
| "OFFICE SPACE"
| "COUNTRY CABIN"
| "PENTHOUSE LIVING ROOM"
| "FARMHOUSE"
| "PATIO"
| "RUSTIC DINING ROOM"
| "SUNROOM LIBRARY"
| "RUSTIC KITCHEN"
| "ATTIC STUDY"
| "ATRIUM"
| "RUSTIC MUSIC ROOM"
| "HOTEL RESTAURANT"
| "PARISIAN LIVING ROOM"
| "ATTIC OFFICE"
| "CABIN BEDROOM"
| "GUEST ROOM"
| "SUNROOM KITCHEN"
| "HOME THEATER"
| "RUSTIC LIBRARY"
| "RUSTIC BEDROOM"
| "OFFICE CAFE"
| "ATTIC BEDROOM"
| "BEACH RESTAURANT"
| "OUTDOOR POOL"
| "HOTEL LOUNGE"
| "YURT"
| "LIGHTHOUSE LIVING ROOM"
| "COTTAGE LIVING ROOM"
| "YACHT KITCHEN"
| "RUSTIC BATHROOM"
| "UNDERGROUND BUNKER"
| "SPA"
| "AIRPORT LOUNGE"
| "RUSTIC LIVING ROOM"
| "HOTEL LOBBY"
| "MANSION LOBBY"
| "OUTDOOR CINEMA"
| "PRIVATE ROOFTOP"
| "GARDEN EXTENSION"
| "LOFT"
| "CRUISE LOUNGE"
| "CHURCH APARTMENT"
| "VICTORIAN BATHROOM"
| "EXTERIOR RANCH HOME"
| "CLOCK TOWER APARTMENT"
| "ARABIC HOUSE EXTERIOR"
| "PARISIAN LIVING ROOM"
| "EXTERIOR VILLA"
| "ENGLISH BEDROOM"
| "EXTERIOR BARN HOUSE"
| "ARABIC INDOOR POOL"
| "EXTERIOR SHOPPING MALL"
| "SALOON INTERIOR"
| "VILLA ENTRANCE"
| "ARABIC LIVING ROOM (MAJLIS)";

export const themes: themeType[] = [
  "Modern",
  "Minimalist",
  "Professional",
  "Tropical",
  "Vintage",
];
export const rooms: roomType[] = [
    "LIVING ROOM",
    "INDOOR POOL",
    "OCEAN VIEW VILLA",
    "CHILDREN'S ROOM",
    "MODERN KITCHEN",
    "LUXURY BATHROOM",
    "HOME OFFICE",
    "MODERN BEDROOM",
    "COURTYARD",
    "OUTDOOR CAFETERIA",
    "ATTIC KITCHEN - MARUTI",
    "BACKYARD GARDEN",
    "TROPICAL BATHROOM",
    "LUXURY BEDROOM",
    "LUXURY YACHT",
    "BOHEMIAN BEDROOM",
    "RESTAURANT",
    "LUXURY HOTEL RECEPTION",
    "INDIAN LIVING ROOM",
    "MODERN LIVING ROOM",
    "LUXURY BATHROOM",
    "INDIAN KITCHEN",
    "LUXURY DINING ROOM",
    "SUN ROOM",
    "BASEMENT",
    "LUXURY GARAGE",
    "CLUB HOUSE",
    "VICTORIAN MUSIC ROOM",
    "CONFERENCE ROOM",
    "HOME CASINO",
    "MINI MART",
    "MOROCCAN KITCHEN",
    "BABY BOY'S ROOM",
    "DENTIST RECEPTION AREA",
    "LAUNDRY ROOM",
    "ATTIC",
    "ARCADE LOUNGE",
    "HOME GYM",
    "SALON",
    "HOME LIBRARY",
    "OFFICE CABIN",
    "PRIVATE STUDY ROOM",
    "TERRACE",
    "HOTEL ROOM",
    "OFFICE LIBRARY",
    "RUSTIC CABIN",
    "RESTAURANT",
    "OFFICE LOBBY",
    "MODERN BEACH HOUSE",
    "TEA ROOM",
    "MODERN MUSIC ROOM",
    "OFFICE LOUNGE",
    "BALCONY",
    "TREE HOUSE",
    "OFFICE SPACE",
    "COUNTRY CABIN",
    "PENTHOUSE LIVING ROOM",
    "FARMHOUSE",
    "PATIO",
    "RUSTIC DINING ROOM",
    "SUNROOM LIBRARY",
    "RUSTIC KITCHEN",
    "ATTIC STUDY",
    "ATRIUM",
    "RUSTIC MUSIC ROOM",
    "HOTEL RESTAURANT",
    "PARISIAN LIVING ROOM",
    "ATTIC OFFICE",
    "CABIN BEDROOM",
    "GUEST ROOM",
    "SUNROOM KITCHEN",
    "HOME THEATER",
    "RUSTIC LIBRARY",
    "RUSTIC BEDROOM",
    "OFFICE CAFE",
    "ATTIC BEDROOM",
    "BEACH RESTAURANT",
    "OUTDOOR POOL",
    "HOTEL LOUNGE",
    "YURT",
    "LIGHTHOUSE LIVING ROOM",
    "COTTAGE LIVING ROOM",
    "YACHT KITCHEN",
    "RUSTIC BATHROOM",
    "UNDERGROUND BUNKER",
    "SPA",
    "AIRPORT LOUNGE",
    "RUSTIC LIVING ROOM",
    "HOTEL LOBBY",
    "MANSION LOBBY",
    "OUTDOOR CINEMA",
    "PRIVATE ROOFTOP",
    "GARDEN EXTENSION",
    "LOFT",
    "CRUISE LOUNGE",
    "CHURCH APARTMENT",
    "VICTORIAN BATHROOM",
    "EXTERIOR RANCH HOME",
    "CLOCK TOWER APARTMENT",
    "ARABIC HOUSE EXTERIOR",
    "PARISIAN LIVING ROOM",
    "EXTERIOR VILLA",
    "ENGLISH BEDROOM",
    "EXTERIOR BARN HOUSE",
    "ARABIC INDOOR POOL",
    "EXTERIOR SHOPPING MALL",
    "SALOON INTERIOR",
    "VILLA ENTRANCE",
    "ARABIC LIVING ROOM (MAJLIS)"
];

